
import java.awt.CardLayout;
//import java.awt.event.ActionListener;
//import java.util.Timer;
//import java.util.TimerTask;
import javax.swing.DefaultListModel;
//import  javax.swing.Timer;
//import javax.swing.event.ListSelectionEvent;
//import java.util.Random;
//import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kieran Bingham & Cameron Sokalski
 */

//Test
public class JeopardyGUI extends javax.swing.JFrame {
    Multiplication multi = new Multiplication();
    MyTimer timer = new MyTimer(); 
    boolean done;

    /**
     * Creates new form JeopardyGUI
     */
    public JeopardyGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        splashScreen = new javax.swing.JPanel();
        titleImage = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        settingsPage = new javax.swing.JPanel();
        toolBarSettings = new javax.swing.JPanel();
        titleImage2 = new javax.swing.JLabel();
        menuButton1 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        addTitle = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        settingsTitle = new javax.swing.JLabel();
        doubleRadio = new javax.swing.JRadioButton();
        timerSlider = new javax.swing.JSlider();
        sliderLabel = new javax.swing.JLabel();
        timerTitle = new javax.swing.JLabel();
        playerList = new javax.swing.JList();
        removeButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        playersError = new javax.swing.JLabel();
        gamePage = new javax.swing.JPanel();
        questionOneLabel = new javax.swing.JLabel();
        toolBar = new javax.swing.JPanel();
        titleImage1 = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        questionOneLabel1 = new javax.swing.JLabel();
        questionOneLabel2 = new javax.swing.JLabel();
        questionOneLabel3 = new javax.swing.JLabel();
        q1Button = new javax.swing.JButton();
        q2Button = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        scoreSeperator = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jButton19.setText("$200");
        jButton19.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton19.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton19.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton20.setText("$400");
        jButton20.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton20.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton20.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton21.setText("$600");
        jButton21.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton21.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton21.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton22.setText("$800");
        jButton22.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton22.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton22.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton23.setText("$1000");
        jButton23.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton23.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton23.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton24.setText("$200");
        jButton24.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton24.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton24.setPreferredSize(new java.awt.Dimension(121, 50));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JEOPARDY!  by: Kieran & Cameron");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(700, 500));
        mainPanel.setLayout(new java.awt.CardLayout());

        splashScreen.setBackground(new java.awt.Color(0, 0, 153));
        splashScreen.setPreferredSize(new java.awt.Dimension(700, 500));

        titleImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resorces/Jeopardy!_Logo_crop.png"))); // NOI18N

        mainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mainMenuButton.setText("Play");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout splashScreenLayout = new javax.swing.GroupLayout(splashScreen);
        splashScreen.setLayout(splashScreenLayout);
        splashScreenLayout.setHorizontalGroup(
            splashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashScreenLayout.createSequentialGroup()
                .addGroup(splashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(splashScreenLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(splashScreenLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(titleImage, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        splashScreenLayout.setVerticalGroup(
            splashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashScreenLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(titleImage)
                .addGap(111, 111, 111)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );

        mainPanel.add(splashScreen, "card1");

        settingsPage.setBackground(new java.awt.Color(0, 0, 153));

        titleImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resorces/small_Logo_crop.png"))); // NOI18N
        titleImage2.setPreferredSize(new java.awt.Dimension(103, 50));

        menuButton1.setFont(menuButton1.getFont().deriveFont(menuButton1.getFont().getStyle() | java.awt.Font.BOLD, menuButton1.getFont().getSize()+3));
        menuButton1.setText("Main Menu");
        menuButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(evt);
            }
        });

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton30.setText("Credits");

        javax.swing.GroupLayout toolBarSettingsLayout = new javax.swing.GroupLayout(toolBarSettings);
        toolBarSettings.setLayout(toolBarSettingsLayout);
        toolBarSettingsLayout.setHorizontalGroup(
            toolBarSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarSettingsLayout.createSequentialGroup()
                .addComponent(titleImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton30)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        toolBarSettingsLayout.setVerticalGroup(
            toolBarSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(toolBarSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(menuButton1)
                .addComponent(jButton30))
        );

        addTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addTitle.setForeground(new java.awt.Color(255, 255, 255));
        addTitle.setText("Add team/player: ");

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        nameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameField.setMaximumSize(new java.awt.Dimension(6, 23));
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        settingsTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        settingsTitle.setForeground(new java.awt.Color(255, 255, 255));
        settingsTitle.setText("<html><u>Settings");

        doubleRadio.setBackground(new java.awt.Color(0, 0, 153));
        doubleRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doubleRadio.setForeground(new java.awt.Color(255, 255, 255));
        doubleRadio.setText("Double Jeopardy");
        doubleRadio.setToolTipText("");

        timerSlider.setBackground(new java.awt.Color(0, 0, 153));
        timerSlider.setMajorTickSpacing(5);
        timerSlider.setMaximum(120);
        timerSlider.setMinimum(10);
        timerSlider.setPaintTicks(true);
        timerSlider.setSnapToTicks(true);
        timerSlider.setValue(30);
        timerSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timerSliderStateChanged(evt);
            }
        });

        sliderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sliderLabel.setForeground(new java.awt.Color(255, 255, 255));
        sliderLabel.setText("30 seconds");

        timerTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timerTitle.setForeground(new java.awt.Color(255, 255, 255));
        timerTitle.setText("<html><u>Timer length: ");

        playerList.setBackground(new java.awt.Color(0, 0, 153));
        playerList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Players", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        playerList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerList.setForeground(new java.awt.Color(255, 255, 255));
        playerList.setModel(new DefaultListModel());
        playerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        playerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerListMouseClicked(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.setEnabled(false);

        goButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        goButton.setText("GO!");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        playersError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playersError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout settingsPageLayout = new javax.swing.GroupLayout(settingsPage);
        settingsPage.setLayout(settingsPageLayout);
        settingsPageLayout.setHorizontalGroup(
            settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBarSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(goButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPageLayout.createSequentialGroup()
                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settingsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doubleRadio)
                            .addGroup(settingsPageLayout.createSequentialGroup()
                                .addComponent(timerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderLabel))
                            .addComponent(timerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(settingsPageLayout.createSequentialGroup()
                                .addComponent(playersError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButton))
                            .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPageLayout.createSequentialGroup()
                                    .addComponent(addTitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addButton))
                                .addComponent(playerList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        settingsPageLayout.setVerticalGroup(
            settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPageLayout.createSequentialGroup()
                .addComponent(toolBarSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPageLayout.createSequentialGroup()
                        .addComponent(settingsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doubleRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderLabel)))
                    .addComponent(playerList, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTitle)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton)
                    .addComponent(editButton)
                    .addComponent(playersError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(goButton)
                .addContainerGap())
        );

        mainPanel.add(settingsPage, "card4");

        gamePage.setBackground(new java.awt.Color(0, 0, 153));
        gamePage.setFocusTraversalPolicyProvider(true);
        gamePage.setMaximumSize(new java.awt.Dimension(121, 50));
        gamePage.setMinimumSize(new java.awt.Dimension(121, 23));
        gamePage.setPreferredSize(new java.awt.Dimension(700, 500));

        questionOneLabel.setFont(questionOneLabel.getFont().deriveFont(questionOneLabel.getFont().getStyle() | java.awt.Font.BOLD, questionOneLabel.getFont().getSize()+6));
        questionOneLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionOneLabel.setText("Multiplication");

        titleImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resorces/small_Logo_crop.png"))); // NOI18N
        titleImage1.setPreferredSize(new java.awt.Dimension(103, 50));

        menuButton.setFont(menuButton.getFont().deriveFont(menuButton.getFont().getStyle() | java.awt.Font.BOLD, menuButton.getFont().getSize()+3));
        menuButton.setText("Main Menu");
        menuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Credits");

        javax.swing.GroupLayout toolBarLayout = new javax.swing.GroupLayout(toolBar);
        toolBar.setLayout(toolBarLayout);
        toolBarLayout.setHorizontalGroup(
            toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarLayout.createSequentialGroup()
                .addComponent(titleImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toolBarLayout.setVerticalGroup(
            toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(menuButton)
                .addComponent(jButton8))
        );

        questionOneLabel1.setFont(questionOneLabel1.getFont().deriveFont(questionOneLabel1.getFont().getStyle() | java.awt.Font.BOLD, questionOneLabel1.getFont().getSize()+10));
        questionOneLabel1.setForeground(new java.awt.Color(255, 255, 255));
        questionOneLabel1.setText("Addition");

        questionOneLabel2.setFont(questionOneLabel2.getFont().deriveFont(questionOneLabel2.getFont().getStyle() | java.awt.Font.BOLD, questionOneLabel2.getFont().getSize()+10));
        questionOneLabel2.setForeground(new java.awt.Color(255, 255, 255));
        questionOneLabel2.setText("Subtration");

        questionOneLabel3.setFont(questionOneLabel3.getFont().deriveFont(questionOneLabel3.getFont().getStyle() | java.awt.Font.BOLD, questionOneLabel3.getFont().getSize()+10));
        questionOneLabel3.setForeground(new java.awt.Color(255, 255, 255));
        questionOneLabel3.setText("Division");

        q1Button.setText("$200");
        q1Button.setMaximumSize(new java.awt.Dimension(121, 50));
        q1Button.setMinimumSize(new java.awt.Dimension(121, 23));
        q1Button.setPreferredSize(new java.awt.Dimension(121, 50));
        q1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ButtonActionPerformed(evt);
            }
        });

        q2Button.setText("$400");
        q2Button.setMaximumSize(new java.awt.Dimension(121, 50));
        q2Button.setMinimumSize(new java.awt.Dimension(121, 23));
        q2Button.setPreferredSize(new java.awt.Dimension(121, 50));
        q2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ButtonActionPerformed(evt);
            }
        });

        jButton5.setText("$600");
        jButton5.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton6.setText("$800");
        jButton6.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton7.setText("$1000");
        jButton7.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton7.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton9.setText("$200");
        jButton9.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton9.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton10.setText("$400");
        jButton10.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton10.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton10.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton11.setText("$600");
        jButton11.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton11.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton12.setText("$800");
        jButton12.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton12.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton12.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton13.setText("$1000");
        jButton13.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton13.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton13.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton14.setText("$200");
        jButton14.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton14.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton14.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton15.setText("$400");
        jButton15.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton15.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton15.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton16.setText("$600");
        jButton16.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton16.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton16.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton17.setText("$800");
        jButton17.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton17.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton17.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton18.setText("$1000");
        jButton18.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton18.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton18.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton25.setText("$400");
        jButton25.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton25.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton25.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton26.setText("$600");
        jButton26.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton26.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton26.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton27.setText("$800");
        jButton27.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton27.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton27.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton28.setText("$1000");
        jButton28.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton28.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton28.setPreferredSize(new java.awt.Dimension(121, 50));

        jButton29.setText("$200");
        jButton29.setMaximumSize(new java.awt.Dimension(121, 50));
        jButton29.setMinimumSize(new java.awt.Dimension(121, 23));
        jButton29.setPreferredSize(new java.awt.Dimension(121, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(143, 14));
        jPanel1.setMinimumSize(new java.awt.Dimension(143, 14));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name of team 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("$10000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel5.setForeground(new java.awt.Color(0, 0, 153));
        jPanel5.setMaximumSize(new java.awt.Dimension(143, 14));
        jPanel5.setMinimumSize(new java.awt.Dimension(143, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name of team 2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("$10000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 153));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel6.setForeground(new java.awt.Color(0, 0, 153));
        jPanel6.setMaximumSize(new java.awt.Dimension(143, 14));
        jPanel6.setMinimumSize(new java.awt.Dimension(143, 14));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name of team 3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("$10000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 153));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel7.setForeground(new java.awt.Color(0, 0, 153));
        jPanel7.setMaximumSize(new java.awt.Dimension(143, 14));
        jPanel7.setMinimumSize(new java.awt.Dimension(143, 14));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name of team 4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("$10000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePageLayout = new javax.swing.GroupLayout(gamePage);
        gamePage.setLayout(gamePageLayout);
        gamePageLayout.setHorizontalGroup(
            gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(gamePageLayout.createSequentialGroup()
                .addComponent(scoreSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(gamePageLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionOneLabel)
                    .addComponent(q1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePageLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePageLayout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(gamePageLayout.createSequentialGroup()
                                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))))
                    .addGroup(gamePageLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(questionOneLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionOneLabel2)
                    .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gamePageLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(questionOneLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        gamePageLayout.setVerticalGroup(
            gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePageLayout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePageLayout.createSequentialGroup()
                        .addComponent(questionOneLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePageLayout.createSequentialGroup()
                        .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gamePageLayout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(gamePageLayout.createSequentialGroup()
                                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(questionOneLabel2)
                                    .addComponent(questionOneLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gamePageLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(questionOneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(q2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(gamePage, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.next(mainPanel);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.previous(mainPanel);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void q1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ButtonActionPerformed
        multi.multiplyLevel1(); 
        q1Button.setEnabled(false);
    }//GEN-LAST:event_q1ButtonActionPerformed

    private void q2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ButtonActionPerformed
        multi.multiplyLevel2();
        q1Button.setEnabled(false);
    }//GEN-LAST:event_q2ButtonActionPerformed

    private void menuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton1ActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.previous(mainPanel);
    }//GEN-LAST:event_menuButton1ActionPerformed

    private void timerSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_timerSliderStateChanged
        sliderLabel.setText(String.valueOf(timerSlider.getValue()) + " seconds");
        timer.setSecs(timerSlider.getValue());
    }//GEN-LAST:event_timerSliderStateChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //timer.countdown();
        DefaultListModel model = (DefaultListModel) playerList.getModel();
        if (model.getSize() >= 4){
//            playersError.setText("Max 4 players");
//            while (playersError.getText() != "Max 4 players"){
//                playersError.setText("Max 4 players");
//            }
//            timer.coundtdownFrom(10);
//            while (timer.checkFinished() == false){
//                playersError.setText("Max 4 players");
//            }
//            Process.waitFor(timer.coundtdownFrom(10));
            playersError.setText("Max 4 players");
        } else {
            if (!"".equals(nameField.getText())) {
                model.addElement(nameField.getText().replaceAll("[ \\t]+", " "));
                nameField.setText("");
                playersError.setText("");
                if (model.getSize() >= 4){
                    addButton.setEnabled(false);
                }
            } else {
                playersError.setText("You can't add a blank name");
            }
        }
        //System.out.println(timer.coundtdownFrom(5));
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        playersError.setText("");
        addButton.setEnabled(true);
        DefaultListModel model = (DefaultListModel) playerList.getModel();
        int index = playerList.getSelectedIndex();
        model.remove(index);
        int size = model.getSize();
        if (size == 0) { //Nobody's left, disable
            removeButton.setEnabled(false);
            editButton.setEnabled(false);
        } else { //Select an index.
            if (index == model.getSize()) {
                //removed item in last position
                index--;
            }
            playerList.setSelectedIndex(index);
            playerList.ensureIndexIsVisible(index);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void playerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerListMouseClicked
        playersError.setText("");
        if (playerList.getSelectedIndex() == -1) {
            editButton.setEnabled(false);
            removeButton.setEnabled(false);
        } else {
            editButton.setEnabled(true);
            removeButton.setEnabled(true);
        }
    }//GEN-LAST:event_playerListMouseClicked

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        playersError.setText("");
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.next(mainPanel);
    }//GEN-LAST:event_goButtonActionPerformed

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped

    }//GEN-LAST:event_nameFieldKeyTyped

    private void nameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyPressed

    }//GEN-LAST:event_nameFieldKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeopardyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeopardyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeopardyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeopardyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeopardyGUI().setVisible(true);
            }
        }); 
    }

    // <editor-fold defaultstate="collapsed" desc="Variables declaration - do not modify"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addTitle;
    private javax.swing.JRadioButton doubleRadio;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel gamePage;
    private javax.swing.JButton goButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton menuButton1;
    private javax.swing.JTextField nameField;
    private javax.swing.JList playerList;
    private javax.swing.JLabel playersError;
    private javax.swing.JButton q1Button;
    private javax.swing.JButton q2Button;
    private javax.swing.JLabel questionOneLabel;
    private javax.swing.JLabel questionOneLabel1;
    private javax.swing.JLabel questionOneLabel2;
    private javax.swing.JLabel questionOneLabel3;
    private javax.swing.JButton removeButton;
    private javax.swing.JSeparator scoreSeperator;
    private javax.swing.JPanel settingsPage;
    private javax.swing.JLabel settingsTitle;
    private javax.swing.JLabel sliderLabel;
    private javax.swing.JPanel splashScreen;
    private javax.swing.JSlider timerSlider;
    private javax.swing.JLabel timerTitle;
    private javax.swing.JLabel titleImage;
    private javax.swing.JLabel titleImage1;
    private javax.swing.JLabel titleImage2;
    private javax.swing.JPanel toolBar;
    private javax.swing.JPanel toolBarSettings;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
